src/Zenweb/Aventure/ParcBundle/Entity/SalesFlatOrder.php
<?php

namespace Zenweb\Aventure\ParcBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * SalesFlatOrder
 */
class SalesFlatOrder
{
    const STATUS_OPEN = 0; // created but not validated
    const STATUS_PENDING = 1; // waiting from action from the user
    const STATUS_VALIDATED = 2; // the order is validated does not mean the payment is ok
    const STATUS_CANCELLED = 3; // the order is cancelled
    const STATUS_ERROR = 4; // the order has an error
    const STATUS_STOPPED = 5; // use if the subscription has been cancelled/stopped
    const STATUS_PAYMENT_ARRIVAL = 6; // use if the user choose to pay on arrival at site
    const STATUS_PAYMENT_CB_PENDING = 9; // use if the user want to pay in CB but nothing after go to bank
    const STATUS_PAYMENT_CB_OK = 7; // use if the user has paid in CB ans return code from bank is ok
    const STATUS_PAYMENT_CB_KO = 8; // use if the user has paid in CB ans return code from bank is ko

    /**
     * @var string $reference
     */
    protected $reference;

    /**
     * @var integer
     */
    private $id;

    /**
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @var string
     */
    private $state;

    /**
     * @var string
     */
    private $status;

    /**
     * @var string
     */
    private $baseTotal;

    /**
     * @var string
     */
    private $baseTotalPaid;

    /**
     * @var string
     */
    private $parc;

    /**
     * @var \DateTime
     */
    private $bookingDate;

    /**
     * @var string
     */
    private $checkoutMethod;

    /**
     * @var string
     */
    private $comment;

    /**
     * @var string
     */
    private $couponCode;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return SalesFlatOrder
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     *
     * @return SalesFlatOrder
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set state
     *
     * @param string $state
     *
     * @return SalesFlatOrder
     */
    public function setState($state)
    {
        $this->state = $state;

        return $this;
    }

    /**
     * Get state
     *
     * @return string
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Set status
     *
     * @param string $status
     *
     * @return SalesFlatOrder
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set baseTotal
     *
     * @param string $baseTotal
     *
     * @return SalesFlatOrder
     */
    public function setBaseTotal($baseTotal)
    {
        $this->baseTotal = $baseTotal;

        return $this;
    }

    /**
     * Get baseTotal
     *
     * @return string
     */
    public function getBaseTotal()
    {
        return $this->baseTotal;
    }

    /**
     * Set baseTotalPaid
     *
     * @param string $baseTotalPaid
     *
     * @return SalesFlatOrder
     */
    public function setBaseTotalPaid($baseTotalPaid)
    {
        $this->baseTotalPaid = $baseTotalPaid;

        return $this;
    }

    /**
     * Get baseTotalPaid
     *
     * @return string
     */
    public function getBaseTotalPaid()
    {
        return $this->baseTotalPaid;
    }

    /**
     * Set parc
     *
     * @param string $parc
     *
     * @return SalesFlatOrder
     */
    public function setParc($parc)
    {
        $this->parc = $parc;

        return $this;
    }

    /**
     * Get parc
     *
     * @return string
     */
    public function getParc()
    {
        return $this->parc;
    }

    /**
     * Set bookingDate
     *
     * @param \DateTime $bookingDate
     *
     * @return SalesFlatOrder
     */
    public function setBookingDate($bookingDate)
    {
        $this->bookingDate = $bookingDate;

        return $this;
    }

    /**
     * Get bookingDate
     *
     * @return \DateTime
     */
    public function getBookingDate()
    {
        return $this->bookingDate;
        //return $this->bookingDate->format('Y-m-d');
    }

    /**
     * Set checkoutMethod
     *
     * @param string $checkoutMethod
     *
     * @return SalesFlatOrder
     */
    public function setCheckoutMethod($checkoutMethod)
    {
        $this->checkoutMethod = $checkoutMethod;

        return $this;
    }

    /**
     * Get checkoutMethod
     *
     * @return string
     */
    public function getCheckoutMethod()
    {
        return $this->checkoutMethod;
    }

    /**
     * Set comment
     *
     * @param string $comment
     *
     * @return SalesFlatOrder
     */
    public function setComment($comment)
    {
        $this->comment = $comment;

        return $this;
    }

    /**
     * Get comment
     *
     * @return string
     */
    public function getComment()
    {
        return $this->comment;
    }

    /**
     * Set couponCode
     *
     * @param string $couponCode
     *
     * @return SalesFlatOrder
     */
    public function setCouponCode($couponCode)
    {
        $this->couponCode = $couponCode;

        return $this;
    }

    /**
     * Get couponCode
     *
     * @return string
     */
    public function getCouponCode()
    {
        return $this->couponCode;
    }

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $items;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $extras;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->setStatus(SalesFlatOrder::STATUS_OPEN);
        $this->items = new \Doctrine\Common\Collections\ArrayCollection();
        $this->extras = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add items
     *
     * @param \Zenweb\Aventure\ParcBundle\Entity\SalesFlatItem $items
     *
     * @return SalesFlatOrder
     */
    public function addItem(\Zenweb\Aventure\ParcBundle\Entity\SalesFlatItem $items)
    {
        $items->setOrder($this);
        $this->items[] = $items;

        return $this;
    }

    /**
     * Remove items
     *
     * @param \Zenweb\Aventure\ParcBundle\Entity\SalesFlatItem $items
     */
    public function removeItem(\Zenweb\Aventure\ParcBundle\Entity\SalesFlatItem $items)
    {
        $this->items->removeElement($items);
    }

    /**
     * Get items
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getItems()
    {
        return $this->items;
    }

    private $booking;

    /**
     * @param mixed $booking
     */
    public function setBooking($booking)
    {
        $this->booking = $booking;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getBooking()
    {
        return $this->booking;
    }


    /**
     * @var \Zenweb\Aventure\ParcBundle\Entity\User
     */
    private $user;


    /**
     * Set user
     *
     * @param \Zenweb\Aventure\ParcBundle\Entity\User $user
     *
     * @return SalesFlatOrder
     */
    public function setUser(\Zenweb\Aventure\ParcBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \Zenweb\Aventure\ParcBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    public function updatedTimestamps()
    {
        $this->setUpdatedAt(new \DateTime('now'));

        if ($this->getCreatedAt() == null) {
            $this->setCreatedAt(new \DateTime('now'));
        }
    }

    /**
     * Calculate order total based on its items
     */
    public function calculateTotal()
    {
        $orderTotal = 0;
        foreach ($this->items as $item) {
            $orderTotal += $item->getRowTotal();
        }
        foreach ($this->extras as $item) {
            $orderTotal += $item->getRowTotal();
        }
        $this->setBaseTotal($orderTotal);
    }

    /**
     * {@inheritdoc}
     */
    public function __toString()
    {
        return $this->getReference() ? : 'n/a';
    }

    /**
     * {@inheritdoc}
     */
    public function setReference($reference)
    {
        $this->reference = $reference;
    }

    /**
     * {@inheritdoc}
     */
    public function getReference()
    {
        return $this->reference;
    }

    /**
     * @return string
     */
    public function getStatusName()
    {
        $statusList = self::getStatusList();

        return $statusList[$this->getStatus()];
    }

    /**
     * @static
     * @return array
     */
    public static function getStatusList()
    {
        return array(
            self::STATUS_OPEN               => 'status_open',
            self::STATUS_PENDING            => 'status_pending',
            self::STATUS_VALIDATED          => 'status_validated',
            self::STATUS_CANCELLED          => 'status_cancelled',
            self::STATUS_ERROR              => 'status_error',
            self::STATUS_STOPPED            => 'status_stopped',
            self::STATUS_PAYMENT_ARRIVAL    => 'status_payment_arrival',
            self::STATUS_PAYMENT_CB_PENDING => 'status_payment_pending',

src/Zenweb/Aventure/ParcBundle/Resources/views/Block/block_calendar.html.twig
{% extends 'SonataBlockBundle:Block:block_base.html.twig' %}
{% block block %}
    {{ render(controller('ZenwebAventureParcBundle:Calendar:calendarDisplay', { 'admin': true })) }}
{% endblock %}

src/Zenweb/Aventure/ParcBundle/Resources/views/Block/recent_orders.html.twig
{% extends sonata_block.templates.block_base %}

{% block block %}
    <div class="sonata-order-block-recent-order panel panel-default">
        {% if settings.title %}
            <div class="panel-heading">
                <div class="panel-title">
                    <h4 class="sonata-order-block-recent-order">{{ settings.title }}</h4>
                </div>
            </div>
        {% endif %}


        {% if orders|length > 0 %}
            <table class="sonata-order-block-order-container table table-condensed">
                {% for order in orders %}
                    <tr>
                        {% if context.getSetting('mode') == 'admin' %}
                            <td><a href="{{ url('admin_aventure_parc_salesflatorder_edit', { 'id': order.id }) }}">{{ order.reference }}</a></td>
                        {% else %}
                            <td><a href="{{ url('sonata_order_view', { 'reference': order.reference }) }}">{{ order.reference }}</a></td>
                        {% endif %}
                        <td class="number">{{ order.baseTotal|number_format }}</td>
                        <td><span class="label{{ order|sonata_status_class(null, 'danger') ? ' label-'~order|sonata_status_class(null, 'danger') : '' }}">{{ order.statusName|trans([], 'SonataOrderBundle') }}</span></td>
                        <td>{{ order.createdAt|date("d/m/Y", "Europe/Paris") }}</td>
                    </tr>
                {% endfor %}
            </table>
            <div class="panel-body">
                {% if context.getSetting('mode') == 'admin' %}
                    <a href="{{ url('admin_aventure_parc_salesflatorder_list') }}" class="btn btn-primary btn-small pull-right"><i class="icon-list icon-white"></i>&nbsp;{{ 'view_all_orders'|trans({}, 'SonataOrderBundle') }}</a>
                {% else %}
                    <a href="{{ url('sonata_order_index') }}" class="btn btn-primary btn-small pull-right"><i class="glyphicon glyphicon-list icon-white"></i>&nbsp;{{ 'view_all_orders'|trans({}, 'SonataOrderBundle') }}</a>
                {% endif %}
            </div>
        {% else %}
            <div class="panel-body">
                {% if context.getSetting('mode') == 'admin' %}
                    <p>{{ 'no_order_found'|trans({}, 'SonataOrderBundle') }}</p>
                {% else %}
                    <p>{{ 'sonata.order.list.no_orders'|trans({}, 'SonataOrderBundle') }}</p>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock %}